#!/bin/bash
if [[ ! -e "$1" ]]; then
  echo "Need a path to the syslog file or directory of syslog files."
  exit 1
fi

rm -rf classes
mkdir -p classes
javac -d classes -cp pig.jar LOG2.java &&
javac -d classes -cp pig.jar WordedSyslog.java &&
cd classes &&
jar cvf ../nodeinfo.jar nodeinfo/*.class &&
cd ..

rm -f numofnodes.dat
pig -p syslogfilepath=$1 -x local ~/projects/nodeinfo/nodecount.pig &&
pig -p numofnodes=`cat numofnodes.dat` -p syslogfilepath=$1 -x local ~/projects/nodeinfo/nodeinfo.pig
